name: Security Checks

on:
  workflow_dispatch:
    inputs:
      testClassName:
        description: 'Specify the test class name to run dynamic checks'
        required: true
        default: 'DefaultTestClass'

  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  Dependency_Scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Scan Dependencies
        run: |
          curl -sSL https://get.snyk.io | bash
          snyk test

  Static_Code_Security:
    name: Static Application Security Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: ['javascript', 'python', 'java']
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  Secrets_Check:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Secrets Scan
        run: trufflehog filesystem --directory=.

  Container_Security:
    name: Container Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Scan Docker Images
        run: |
          curl -fsSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          trivy image my-docker-image:latest

  Dynamic_Test:
    name: Run Dynamic Tests
    runs-on: ubuntu-latest
    needs: [Dependency_Scan, Static_Code_Security, Secrets_Check, Container_Security]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        run: echo "Test Class Name: ${{ github.event.inputs.testClassName }}"
      - name: Run Dynamic Tests
        run: |
          echo "Running tests for class: ${{ github.event.inputs.testClassName }}"
          mvn test -Dtest=${{ github.event.inputs.testClassName }}
