name: E2E Tests Custom

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: 'path/to/defaultTestData.json'  # Default path if none provided

jobs:
  E2E_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Run Tests
        run: |
          mvn test -DtestsPath="${{ github.event.inputs.testsPath }}" # Passing testsPath to the Java test
