name: Security Checks

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Security Tests to be Executed'
        default: ''

jobs:
  Security_Checks_Chrome_Linux:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      # Example: Running Snyk Dependency Scan for Security Vulnerabilities
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        run: snyk test

      # Optional: Example of running static analysis with OWASP Dependency-Check
      - name: Run OWASP Dependency-Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload Allure Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Security_Allure
          path: "allure-report/*_AllureReport.html"

      - name: Upload Execution Summary Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Security_Summary
          path: "execution-summary/ExecutionSummaryReport_*.html"

      - name: Publish Test Results (if available)
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Security Results Chrome_Linux"
          files: |
            target/surefire-reports/TEST-*.xml

  Security_Checks_Firefox_Linux:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        run: snyk test

      - name: Run OWASP Dependency-Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload Allure Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Firefox_Linux_Security_Allure
          path: "allure-report/*_AllureReport.html"

      - name: Upload Execution Summary Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Firefox_Linux_Security_Summary
          path: "execution-summary/ExecutionSummaryReport_*.html"

      - name: Publish Test Results (if available)
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Security Results Firefox_Linux"
          files: |
            target/surefire-reports/TEST-*.xml

  Security_Checks_Edge_Windows:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        run: snyk test

      - name: Run OWASP Dependency-Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload Allure Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Security_Allure
          path: "allure-report/*_AllureReport.html"

      - name: Upload Execution Summary Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Security_Summary
          path: "execution-summary/ExecutionSummaryReport_*.html"

      - name: Publish Test Results (if available)
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          check_name: "Security Results Edge_Windows"
          files: |
            target/surefire-reports/TEST-*.xml

  Security_Checks_Safari_MacOS:
    runs-on: macos-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        run: snyk test

      - name: Run OWASP Dependency-Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload Allure Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Safari_MacOS_Security_Allure
          path: "allure-report/*_AllureReport.html"

      - name: Upload Execution Summary Report as Artifact (if available)
        uses: actions/upload-artifact@v3
        with:
          name: Safari_MacOS_Security_Summary
          path: "execution-summary/ExecutionSummaryReport_*.html"

      - name: Publish Test Results (if available)
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          check_name: "Security Results Safari_MacOS"
          files: |
            target/surefire-reports/TEST-*.xml
