  Dynamic_Test:
    name: Run Dynamic Tests
    runs-on: ubuntu-latest
    needs: [Dependency_Scan, Static_Code_Security, Secrets_Check, Container_Security]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Environment
        run: echo "Test Class Name: ${{ github.event.inputs.testClassName }}"
      - name: Run Dynamic Tests
        shell: bash
        run: |
          echo "Running tests for class: ${{ github.event.inputs.testClassName }}"
          mvn test -Dtest="${{ github.event.inputs.testClassName }}"
